version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --disable-security-middleware
    ports:
      - "5000:5000"

  orchestrator:
    build: 
      context: .
      dockerfile: services/orchestrator/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mlflow
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "project=mlops,service=orchestrator"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

  training-worker:
    build:
      context: .
      dockerfile: services/training_worker/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file: .env
    ports:
      - "8500:8500"
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    depends_on:
      - postgres
      - mlflow
      - minio
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "project=mlops,service=training-worker"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

  inference-service:
    build: 
      context: .
      dockerfile: ./services/inference_service/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    ports:
      - "8001:8001"
    depends_on:
      - mlflow
      - minio
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "project=mlops,service=inference-service"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

  monitoring-service:
    build: 
      context: .
      dockerfile: ./services/monitoring_service/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "project=mlops,service=monitoring-service"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

  monitoring-dashboard:
    build: 
      context: .
      dockerfile: ./services/monitoring_dashboard/Dockerfile
    volumes:
      - ./shared:/app/shared
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: DEBUG
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - loki
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "project=mlops,service=monitoring-dashboard"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s

volumes:
  postgres_data:
  minio_data:
  
