version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --disable-security-middleware
    ports:
      - "5000:5000"

  orchestrator:
    build: ./services/orchestrator
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mlflow

  training-worker:
    build:
      context: .
      dockerfile: services/training_worker/Dockerfile
    env_file: .env
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    depends_on:
      - postgres
      - mlflow
      - minio

  inference-service:
    build: ./services/inference-service
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - mlflow
      - minio
      - postgres

  monitoring-service:
    build: ./services/monitoring-service
    env_file: .env
    ports:
      - "8002:8002"
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio_data:
